### ISSUE TITLE
Missing cop in sentence n01086013

### ISSUE THREAD

**Issue by harisont** [UniversalDependencies/UD_Italian-PUD#1]
I am not sure what the policy for transation is in PUD, but

> Il mondo può furente e assurdo

seems ungrammatical to me. It should be

> Il mondo può _essere_ furente e assurdo

The analysis than becomes much like the English one:

![image](https://github.com/UniversalDependencies/UD_Italian-PUD/assets/17993183/574bbe0c-80a9-4dd6-98ad-589d38c07b56)

**Comment by dan-zeman** [comment]
The translations in PUD have been known to be not always good. Elsewhere in UD the policy is not to correct errors in the underlying text (or better: provide correction in MISC but leave the error in FORM), but this policy does not apply to PUD where the translations were created specifically for the UD project and are thus treated like the annotation: If an error is spotted, it should be fixed.
